###
GET https://collectionapi.metmuseum.org/public/collection/v1/search?hasImages=true&isOnView=true&q=mythology&limit=50

###
GET https://collectionapi.metmuseum.org/public/collection/v1/objects/65576






