###
GET https://collectionapi.metmuseum.org/public/collection/v1/search?hasImages=true&isOnView=true&q=mythology

###
GET https://collectionapi.metmuseum.org/public/collection/v1/objects/558682

###
GET https://www.metmuseum.org/art/collection/search/558682






